### ISSUE TITLE
DSAPublicPem

### ISSUE THREAD

**Issue by Private-Storm** [jkour/neSparkle#5]
Sorry but I'll don't get it.
I'll don't see how the DSA Signature will be validated or is it not implemeented yet?

Can you describe in short how to make validation work?

**Comment by jkour** [comment]
Hi,

The unit is a wrapper for functions in the actual DLL libraries. 

The validation is not done in the unit; You assign the signature to the DSAPublicPem property and it is passed to the method in the DLL, which performs whatever is needed.

Have a look at the implementation of the setDSAPublicPem method.

**Comment by Private-Storm** [comment]
> Hi,
> 
> The unit is a wrapper for functions in the actual DLL libraries.
> 
> The validation is not done in the unit; You assign the signature to the DSAPublicPem property and it is passed to the method in the DLL, which performs whatever is needed.
> 
> Have a look at the implementation of the setDSAPublicPem method.

Hey,
maybe I've misunderstood something here.
What I did:

loaded the complete contents of the public.pem I'v created as string into DSAPublicPem when I try to change the DSA Signature in my Appcast.xml shouldn't I get any validation error or somthing? Because no matter if i put invalid data there or not I receive updates without any issues... That's what makes me ask. Could be I did not get the concept yet though

**Comment by jkour** [comment]
Hey,

TBH I haven't tried how it works myself but from a quick look at the documentation of the original library here: https://github.com/vslavik/winsparkle/blob/master/include/winsparkle.h I get the impression that the check needs to be done explicitly in your application. Also, the example it has, uses a pem file too.

But I am not quite certain of this.

Also this is an addition in a PL so let's ask @gliden for help.

@gliden Can you please help us?

**Comment by Private-Storm** [comment]
> Hey,
> 
> TBH I haven't tried how it works myself but from a quick look at the documentation of the original library here: https://github.com/vslavik/winsparkle/blob/master/include/winsparkle.h I get the impression that the check needs to be done explicitly in your application. Also, the example it has, uses a pem file too.
> 
> But I am not quite certain of this.
> 
> Also this is an addition in a PL so let's ask @gliden for help.
> 
> @gliden Can you please help us?

**"I get the impression that the check needs to be done explicitly in your application."** 

Ah I was afraid to read something like this. My expectation was that the sparkle dll would raise an InvalidSignature Exception or something like that automatically if something is wrong with it.

Would be cool if someone could come up with a more advanced example validating the given signature.

**Comment by gliden** [comment]
Hey,

I looked right now in the code of winsparkle and found that the DLL checks the signature of the downloaded file.
Look at [this line ](https://github.com/vslavik/winsparkle/blob/91bb56ea20eb787c0cbb1f00277f98a4cbef594a/src/updatedownloader.cpp#L183) and also [here](https://github.com/vslavik/winsparkle/blob/91bb56ea20eb787c0cbb1f00277f98a4cbef594a/src/signatureverifier.h#L51).

**Comment by Private-Storm** [comment]
> Hey,
> 
> I looked right now in the code of winsparkle and found that the DLL checks the signature of the downloaded file.
> Look at [this line ](https://github.com/vslavik/winsparkle/blob/91bb56ea20eb787c0cbb1f00277f98a4cbef594a/src/updatedownloader.cpp#L183) and also [here](https://github.com/vslavik/winsparkle/blob/91bb56ea20eb787c0cbb1f00277f98a4cbef594a/src/signatureverifier.h#L51).

Hey,
thats true but somewhat strange to me.

Example: 
My Setup was signed with OpenSSL I've got the DSA and put that into my Appcast.xml something like:

**sparkle:dsaSignature="MEQCID1QkV07X+0** and so on...

In the **neSparkle DSAPublicPem** I've loaded the contents of my Public.Pem file...

Then I've modified **sparkle:dsaSignature="vgbhjnfvwzgudhwfbw"** which should fail but it works fine.
So unless I've completly misunderstood the concept something went strange I guess.

**Comment by jkour** [comment]
@Private-Storm 

I will upload a demo tomorrow

**Comment by Private-Storm** [comment]
@jkour 
That would be cool

**Comment by jkour** [comment]
@Private-Storm 

I updated the demo with DSA signature example. Please check the readme.md in Demos folder.

It looks like the check for valid signature is done after the installer is downloaded.
 
Hope this helps

**Comment by Private-Storm** [comment]
@jkour 
very nice and many thanks for the work you did 
best regrads
